##############################
# AntiHaxerman Configuration #
##############################

########################################################################################################################
# Anticheat testing mode.                                                                                              #
# If enabled, no punishments will occur and alerts will enable automatically on join.                                  #
########################################################################################################################
testmode: false
########################################################################################################################
# Anticheat response configuration.                                                                                    #
# If you want to change how the anticheat looks/responds, you can do it here.                                          #
########################################################################################################################
response:
  anticheat:
    prefix: '&cAHM &8> '
  command:
    prefix: '&cAHM &8> '

########################################################################################################################
# Logging configuration.                                                                                               #
# Logs are still beta and there is a chance it might lag the server so its disabled by default.                        #
########################################################################################################################
logging:
  enabled: false
  log-format: '[%date%] %player% failed %check% (Type %type%)%dev% VL: %vl% [TPS: %tps%] [tPing: %tping% kaPing: %kaping%] [Info: %info%]'

########################################################################################################################
# Bypass settings.                                                                                                     #
# Bypass operators allows people with OP bypass checks.                                                                #
########################################################################################################################
bypass:
  bypass-operators: false

general:
  # Early inject allows us to see client version etc. (Not used so I don't see a point it being enabled.)
  early-inject: false
  # Enable async injection and uninjection. Enabled by default for performance reasons but will cost us reload support. (RECOMMENDED TO KEEP IT ENABLED)
  async-inject-uninject: true

api:
  # API is disabled by default for performance reasons. Recommended to keep disabled unless the API is used.
  enabled: false

violations:
  alert-format: '&cAHM &8> &c%player%&8 failed &c%check% &8(&cType %type%&8)%dev% VL: &c%vl%'
  clear-violations-delay: 15

########################################################################################################################
# Check configuration                                                                                                  #
# enabled: Turns the check on/off.                                                                                     #
# max-violations: Amount of times a player can flag before running the specified punish-command.                       #
# punish-command: Command ran by the server when a player exceeds the specified max-violations.                        #
########################################################################################################################
checks:
  combat:
    aim:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
      e:
        enabled: true
        max-violations: 50
        punish-command: ''
      f:
        enabled: true
        max-violations: 50
        punish-command: ''
      g:
        enabled: true
        max-violations: 50
        punish-command: ''
    aura:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
    autoclicker:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
      e:
        enabled: true
        max-violations: 50
        punish-command: ''
      f:
        enabled: true
        max-violations: 50
        punish-command: ''
    reach:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    angle:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    autoblock:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    velocity:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
  movement:
    speed:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
      e:
        enabled: true
        max-violations: 50
        punish-command: ''
    fastclimb:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    flight:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    strafe:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    motion:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    noslow:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    largemove:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    jesus:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    liquidspeed:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
    omnisprint:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
  player:
    groundspoof:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    timer:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    post:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
      e:
        enabled: true
        max-violations: 50
        punish-command: ''
      f:
        enabled: true
        max-violations: 50
        punish-command: ''
      g:
        enabled: true
        max-violations: 50
        punish-command: ''
    inventory:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    pingspoof:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    fastplace:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    scaffold:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    tower:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    interact:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    badpackets:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
      e:
        enabled: true
        max-violations: 50
        punish-command: ''
      f:
        enabled: true
        max-violations: 50
        punish-command: ''
      g:
        enabled: true
        max-violations: 50
        punish-command: ''
      h:
        enabled: true
        max-violations: 50
        punish-command: ''
      i:
        enabled: true
        max-violations: 50
        punish-command: ''
      j:
        enabled: true
        max-violations: 50
        punish-command: ''
      k:
        enabled: true
        max-violations: 50
        punish-command: ''
      l:
        enabled: true
        max-violations: 50
        punish-command: ''
      m:
        enabled: true
        max-violations: 50
        punish-command: ''
      n:
        enabled: true
        max-violations: 50
        punish-command: ''