##############################
# AntiHaxerman Configuration #
##############################

########################################################################################################################
# Anticheat testing mode.                                                                                              #
# If enabled, no punishments will occur and alerts will enable automatically on join.                                  #
########################################################################################################################
testmode: false
########################################################################################################################
# Anticheat response configuration.                                                                                    #
# If you want to change how the anticheat looks/responds, you can do it here.                                          #
########################################################################################################################
response:
  anticheat:
    prefix: '&cAHM &8> '
  command:
    prefix: '&cAHM &8> '

violations:
  alert-format: '&cAHM &8> &c%player%&8 failed &c%check% &8(&cType %type%&8)%dev% VL: &c%vl%'
  clear-violations-delay: 15

########################################################################################################################
# Check configuration                                                                                                  #
# enabled: Turns the check on/off.                                                                                     #
# max-violations: Amount of times a player can flag before running the specified punish-command.                       #
# punish-command: Command ran by the server when a player exceeds the specified max-violations.                        #
########################################################################################################################
checks:
  combat:
    aim:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    aura:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    autoclicker:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
  movement:
    speed:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    fastclimb:
      a:
        enabled: true
        max-violations: 50
    flight:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
    motion:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    noslow:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    largemove:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    liquidspeed:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
  player:
    groundspoof:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
    timer:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
    post:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''
      e:
        enabled: true
        max-violations: 50
        punish-command: ''
      f:
        enabled: true
        max-violations: 50
        punish-command: ''
    pingspoof:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    blink:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
    badpackets:
      a:
        enabled: true
        max-violations: 50
        punish-command: ''
      b:
        enabled: true
        max-violations: 50
        punish-command: ''
      c:
        enabled: true
        max-violations: 50
        punish-command: ''
      d:
        enabled: true
        max-violations: 50
        punish-command: ''